# This file is used by the #GRADLE_LOCAL_JAVA_HOME macro in Android Studio.
# Replace the path below with your actual JDK path if the default doesn't work.
java.home=C\:\\Program Files\\Android\\Android Studio\\jbr